### ISSUE TITLE
I am trying to run your simulation but it is giving me error for a missing file. Sampling_msgs/StopAgent.h

### ISSUE THREAD

**Issue by AimanMunir** [zyyyyyyyyy/heterogeneous-sampling#4]
src/Heterogeneous-Multi-Robot-Adaptive-Sampling/src/sampling_agent/include/sampling_agent/sampling_agent.h:5:10: fatal error: sampling_msgs/StopAgent.h: No such file or directory
 #include <sampling_msgs/StopAgent.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by yangggzhang** [comment]
It's the header file for one of the services in `sampling_msgs` package. It should be installed when `sampling_msgs` is built. How did you build the project? Are you running `catkin build`?

**Comment by AimanMunir** [comment]
I got it fixed. I was using catkin make and it was building some packages before the others. Thanks for the reply.
